name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GAUGEBOT_GITHUB_TOKEN }}'
      CI: true

    steps:
      - uses: actions/checkout@v2

      - name: Build artifacts
        run: |
          docker build . -t gauge-taiko

      - name: Tag image
        run: |
          docker tag gauge-taiko:latest docker.pkg.github.com/getgauge-examples/gauge-docker/gauge-taiko:$GITHUB_RUN_NUMBER
          docker tag gauge-taiko:latest docker.pkg.github.com/getgauge-examples/gauge-docker/gauge-taiko:latest
          docker images -a
